config/routes.rb
Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/index'
  get 'comments/edit'
  get 'comments/show'
  get 'events/index'
  get 'events/new'
  get 'events/edit/:id' => "events#edit"
  get 'events/destroy/:id' => "events#destroy"
  get 'events/create'
  get 'events/show'
  devise_for :users
  get 'home/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  resources :events, :home, :comments
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  validates :description, presence: true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	has_many :events
	has_many :comments
	validates :title, presence: true, length: {in: 5..20}
	validates :start, presence: true
	validates :end, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :events

   after_create :signup_confirmation
   def signup_confirmation
   	  UserMailer.signup_confirmation(self).deliver
   end
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
  	@comment = Comment.new
  end

  def index
  	@comments = Comment.all
  end

  def create
  	comment = Comment.new
  	comment.description = params[:comment][:description]
  	comment.event_id = params[:comment][:event_id]
  	comment.save
  	redirect_to new_comment_path
  end

  def edit
  end

  # def show
  # 	@comment = Comment.find(params[:id])
  # end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
   if current_user.present?
      @events = Event.all.where(user_id: current_user.id)
      else
    @events = Event.all
    end
  end

  def new
    @event = Event.new
  end

  def create
    event = Event.new
    event.title = params[:event][:title]
    event.start = params[:event][:start]
    event.end = params[:event][:end]
    event.user_id = current_user.id
    if event.save
    redirect_to events_index_path
  else
    redirect_to events_new_path
  end
  end
  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update(title: params[:event][:title],start: params[:event][:start],end: params[:event][:end])
      redirect_to events_index_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to events_index_path
  end

  def show
     @event = Event.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	def link_to_comment(comment)
    link_to(comment.description, comment_path(comment))
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<table width="50%" cellpadding="3" cellspacing="3" border="3" bordercolor="black">
	<caption><b>Comments<br></caption>
   <tr>
   	  <th>Description</th>
   	   <th>Event</th>
    </tr>
  <% @comments.each do |comments| %>
  	<tr>
       <td><%= comments.description %></td>
       <td><%= comments.event_id %></td>
    </tr>
  <% end %>

</table>

app/views/comments/new.html.erb
Add new Comment
<br><br/>
<%= form_for @comment do |comment| %>
description: <%= comment.text_field :description %><br>
<%= comment.collection_select(:event_id, Event.all, :id, :title, prompt: "please select event") %><br>
<br><%= comment.submit%>
<% end %>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/events/edit.html.erb
Edit Event 
<br><br/>
<%= form_for @event do |event| %>
Event Name: <%= event.text_field :title %><br>
Start Date: <%= event.text_field :start %><br>
End Date: <%= event.text_field :end %><br>
<br><%= event.submit%>
<% end %>

app/views/events/index.html.erb
<table width="50%" cellpadding="3" cellspacing="3" border="3" bordercolor="black">
	<caption><b>Events<br></caption>
   <tr>
   	  <th>ID</th>
   	  <th>Name</th>
   	   <th>Start Date</th>
   	    <th>End Date</th>
      <th>Event Detail</th>
   	  
    	</tr>
  <% @events.each do |events| %>
  	<tr>
      <td><%= events.id %></td>
       <td><%= events.title %></td>
       <td><%= events.start %></td>
       <td><%= events.end %></td>
         <td>
            <%= link_to "Edit","/events/edit/#{events.id}" %>
            <%= link_to "Delete","/events/destroy/#{events.id}" %>
          </td>
    </tr>
  <% end %>

</table>
<% if current_user.present? %>
  <%= link_to "Create new event", new_event_path %>
  <% end %>
<div id="calendar"></div>
<script type="text/javascript">
$('#calendar').fullCalendar({
	events: '/events.json'
});
</script>

app/views/events/new.html.erb
Add new Event 
<br><br/>
<%= form_for @event do |event| %>
Event Name: <%= event.text_field :title %><br>
Start Date: <%= event.text_field :start %><br>
End Date: <%= event.text_field :end %><br>
<br><%= event.submit%>
<% end %>

app/views/events/show.html.erb
Id: <%= @event.id %><br>
Event Name: <%= @event.title %><br>
Event Start At: <%= @event.start %><br>
Event End : <%= @event.end %><br>
Event created by : <%= User.where(id: @event.user_id).pluck(:email) %><br>

 <%= link_to "Edit","/events/edit/#{@event.id}" %>
 <%= link_to "comment", new_comment_path %>
 <%= link_to "All comments", comments_path %>

app/views/home/index.html.erb
<header>
	<section class='navsaction'>
		<nav class='nav'>
	<% if user_signed_in? %>
		<%= link_to "Sign out", destroy_user_session_path, method: :delete %>
	<%= current_user.email %>
	<% else %>
		<%= link_to "Sign in", new_user_session_path %>
		<%= link_to "Sign up", new_user_registration_path %>
	<% end %>
<%= link_to "List of Events",events_index_path %>
</nav>
</section>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMS</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>
    <%= yield %>
  </body>
</html>